# Generated by Django 5.0.11 on 2025-01-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('year', models.IntegerField()),
                ('director', models.CharField(default='', max_length=100)),
                ('rating', models.FloatField()),
                ('genre', models.CharField(default='', max_length=100)),
                ('runtime', models.IntegerField()),
                ('description', models.TextField(default='')),
                ('photo', models.ImageField(blank=True, upload_to='photos/')),
            ],
        ),
    ]
