# Generated by Django 5.0.11 on 2025-01-22 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='is_saved',
        ),
    ]
