# Generated by Django 5.1.4 on 2025-01-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
