# Generated by Django 5.1.4 on 2025-01-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_photo_alter_film_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='film',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
